<p style="text-align: center;">LICENCIATURA EN CIENCIAS DE LA COMPUTACIÓN</p>
<p style="text-align: center;">*Métodos Numéricos*</p>
<p style="text-align: center;">**Practica No.5**</p>
<p style="text-align: center;">Nombre: Nicolas Alejandro Baak Poot</p>

**Instrucciones**
<p style="text-align: justify;">
En un Notebook  y usando los recursos de python, crea el proceso para usar la factorización LU implementada en python (scipy, sympy, etc) de manera que permita resolver un sistema de ecuaciones lineales. Aplique su proceso a los sistemas lineales listados en el Conjunto de Ejercicios 6.5 inciso 4.</p>

In [3]:
import scipy.linalg as la
import numpy as np

In [4]:
def factorizacionLU(A, b):
    # Sea A una matriz que se puede escribir de la forma A = LU
    # donde L es ua matriz triangular inferior y U es una matriz escalonada
    # => Sea Ax = b
    # => Ax = (LU)x = L(Ux)
    # Una posible estrategia de solucón consiste en tomar y = Ux y resolver para 'y'
    # => Ly = b
    # luego se resuelve
    # => Ux = y 
    
    # n: número de filas de A
    n = len(A)
    #matriz identidad con n filas
    L = np.identity(n)
    U = np.copy(A)
    y = np.zeros(n)
    x = np.zeros(n)
    
    #Descomposición de A para obtener L y U
    for i in range(0, n-1):
        for j in range(i+1, n):
            L[j, i] = U[j, i]/U[ i, i]
            for k in range(i, n):
                U[j, k] = U[j, k] - L[j, i]*U[i, k]
    
    # teniendo L y U 
    # sea L_inv el inverso multiplicativo de L
    # Ly = b
    # => (L_inv)(L)(y) = (L_inv)(b)
    # => y =  (L_inv)(b)
    L_inv = np.linalg.inv(L)
    y = L_inv @ b
    print(y)
    # sea U_inv el inverso multiplicativo de U
    # (U)(x) = y
    # (U_inv)(U)(x) = (U_inv)(y)
    # x = (U_inv)(y)
    U_inv = np.linalg.inv(U)
    x = U_inv @ y
        
    #procedimiento terminado exitosamente
    x = np.transpose([x])
    return x

In [5]:
#--------------------Ejercicio A------------------------------------
A = np.array([[2, -1, 1],
              [3, 3, 9],
              [3, 3, 5]])

b = np.array([[-1],[0],[4]])

#Ejecutamos el algoritmo y obtenemos el vector resultado x
x = factorizacionLU(A, b)
print("Resultados de x:")
print(x)

[[-1. ]
 [ 1.5]
 [ 4. ]]
Resultados de x:
[[[ 1.0625]
  [ 2.125 ]
  [-1.    ]]]


In [4]:
#comprobando con linalg.solve A
lu, piv = la.lu_factor(A)
x = la.lu_solve((lu, piv), b)

print("Resultados de x:")
print(x)

Resultados de x:
[[ 1.]
 [ 2.]
 [-1.]]


In [5]:
#--------------------Ejercicio B------------------------------------
A = np.array([[1.012, -2.132, 3.104],
              [-2.132, 4.096, -7.013],
              [3.104, -7.013, 0.014]])

b = np.array([[1.984],[-5.049],[-3.895]])

print("Resultados de x:")
x = factorizacionLU(A, b)
print(x)

Resultados de x:
[[[1.]
  [1.]
  [1.]]]


In [6]:
# comprobando con linalg.solve B
lu, piv = la.lu_factor(A)
x = la.lu_solve((lu, piv), b)
print(x)

[[1.]
 [1.]
 [1.]]


In [7]:
#--------------------Ejercicio C------------------------------------
A = np.array([[2, 0, 0, 0],
              [1, 1.5, 0, 0],
              [0, -3, 0.5, 0],
              [2, -2, 1, 1]])

b = np.array([[3],[4.5],[-6.6],[0.8]])

print("Resultados de x:")
x = factorizacionLU(A, b)
print(x)

Resultados de x:
[[[ 1.5]
  [ 2. ]
  [-1.2]
  [ 3. ]]]


In [8]:
#comprobando con linalg.solve C
lu, piv = la.lu_factor(A)
x = la.lu_solve((lu, piv), b)
print(x)

[[ 1.5]
 [ 2. ]
 [-1.2]
 [ 3. ]]


In [9]:
#--------------------Ejercicio D------------------------------------
A = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
              [-4.0231, 6, 0, 1.1973],
              [-1, -5.2107, 1.1111, 0],
              [6.0235, 7, 0, -4.1561]])

b = np.array([[17.102],[-6.1593],[3.0004],[0]])

print("Resultados de x:")
x = factorizacionLU(A, b)
print(x)

Resultados de x:
[[[2.9398512 ]
  [0.0706777 ]
  [5.67773512]
  [4.37981223]]]


In [10]:
#comprobando con linalg.solve D
lu, piv = la.lu_factor(A)
x = la.lu_solve((lu, piv), b)
print(x)

[[2.9398512 ]
 [0.0706777 ]
 [5.67773512]
 [4.37981223]]


# Conclusion: 
Utilizando algunas herramientas del modulo linalg para comprobar mis resultados, puedo observar que mi algoritmo tiene una presición acertada y segun mis investigaciones este algoritmo es mas eficiente para cuando se deben resolver numerosos sistemas con los mismo coeficientes en A pero disitintos terminos en b