<p style="text-align: center;">LICENCIATURA EN CIENCIAS DE LA COMPUTACIÓN</p>
<p style="text-align: center;">*Métodos Numéricos*</p>
<p style="text-align: center;">**Practica No.4**</p>
<p style="text-align: center;">Nombre: Nicolas Alejandro Baak Poot</p>

**Instrucciones**
<p style="text-align: justify;">
Usando eliminación gaussiana con tipos de dato `numpy.half` y `numpy.double` resuelva los siguientes sistemas lineales. También uncuentra la solución usando `scipy.linalg.solve`. Después compara las aproximaciones que obtuviste con la solución real. 
</p>
![Lista de ejercicios](Ejercicio6-2-5.png)

In [119]:
from scipy import linalg, mat
import numpy as np

In [137]:
#Eliminacion gaussiana con sustitución hacia atras
# Entrada: matriz aumentada E y el dtype para el vector solucion
# salida: vector solucion de tamaño n

def Gauss(E, typ):
    #numero de filas de la matriz aumentada
    n = len(E)
    #vector de longitud n
    x = np.zeros(n, dtype=typ)
    
    #proceso de eliminacion
    for i in range(n-1):
        p = i;
        min = abs(E[i,i])
        for ii in range(i+1,n):
            candidato = abs(E[ii, i])
            if candidato > min:
                min = candidato
                p = ii
        if p != i:
            for jj in range(i, n+1):
                temp = E[p, jj]
                E[p, jj] = E[i, jj]
                E[i, jj] = temp
        
        for j in range(i+1, n):
            factor = E[j, i]/E[i][i]
            for k in range(i, n+1):
                E[j, k] = E[j, k] - factor*E[i, k]
    
    #Si a[n][n] = 0 entonces no existe solución unica
    if E[n-1][n-1] == 0:
        print("No existe solución unica")
        exit()

    #Comienza la sustitución hacia atras
    x[n-1] = E[n-1, n]/E[n-1, n-1]
    
    for i in range(n-1, 0-1, -1):
        x[i] = E[i]
        for j in range(i+1, n):
            x[i] = x[i] - E[i, j]*x[j]
        x[i] = x[i]/E[i, i]
    #procedimiento terminado exitosamente
    x = np.transpose([x])
    return x

In [140]:
#calcula el error relativo del vector solucion y retorna un vector con el error relativo
#entrada: vector solucion y vector con los valores reales
#salida: vector con el error relativo de cada elemento del vector solucion

def errorRelativo(x, real):
    resultado = np.zeros(len(x))
    for i in range(len(x)):
        if(real[i]!=0):
            resultado[i] = np.abs(((real[i]-x[i])/real[i]))
        else:
            resultado[i] = np.abs((real[i]-x[i]))
    resultado = np.transpose([resultado])
    return resultado

In [141]:
#=============================Ejercicio A=====================
#Ejercicio A - np.half

A = np.array([[0.03,58.9],[5.31,-6.10]], dtype=np.half)
b = np.array([[59.2],[47.0]], dtype=np.half)
Ab = np.concatenate((A,b),axis=1)

x = Gauss(Ab, np.half)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([10, 1], dtype=np.half))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[10.]
 [ 1.]]

Error Relativo:
[[0.]
 [0.]]


In [157]:
# Ejercicio A - np.double

A = np.array([[0.03,58.9],[5.31,-6.10]], dtype=np.double)
b = np.array([[59.2],[47.0]], dtype=np.double)
Ab = np.concatenate((A,b),axis=1)

x = Gauss(Ab, np.double)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([10, 1], dtype=np.double))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[10.]
 [ 1.]]

Error Relativo:
[[1.776e-16]
 [2.220e-16]]


In [143]:
# linalg.solve
# se obtuvieron los mismos resultados
print(linalg.solve(A,b))

[[10.]
 [ 1.]]


In [144]:
#============================= Ejercicio B =====================
# Ejercicio b - np.half

A = np.array([[58.9,0.03],[-6.10,5.31]], dtype=np.half)
b = np.array([[59.2],[47.0]], dtype=np.half)
Ab = np.concatenate((A,b),axis=1)

x = Gauss(Ab, np.half)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([1, 10], dtype=np.half))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[ 1.]
 [10.]]

Error Relativo:
[[0.]
 [0.]]


In [145]:
# Ejercicio b - np.double
A = np.array([[58.9,0.03],[-6.10,5.31]], dtype=np.double)
b = np.array([[59.2],[47.0]], dtype=np.double)
Ab = np.array([[58.9,0.03,59.2],[-6.10,5.31,47.0]], dtype=np.double)

x = Gauss(Ab, np.double)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([1, 10], dtype=np.double))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[ 1.]
 [10.]]

Error Relativo:
[[2.22e-16]
 [0.00e+00]]


In [146]:
#linalg.solve

print(linalg.solve(A,b))

[[ 1.]
 [10.]]


In [147]:
#============================= Ejercicio C =====================
# Ejercicio c - np.half

A = np.array([[3.03, -12.1, 14],[-3.03, 12.1, -7],[ 6.11, -14.2, 21]], dtype=np.half)
b = np.array([[-119],[120],[-139]], dtype=np.half)
Ab = np.array([[3.03,-12.1, 14, -119],[ -3.03, 12.1, -7, 120],[ 6.11, -14.2, 21, -139]], dtype=np.half)

x = Gauss(Ab, np.half)
print("\nSoluciones:\n{0}".format(x))
resultado = errorRelativo(x, np.array([0, 10, 1/7], dtype=np.half))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[-0.02 ]
 [ 9.99 ]
 [ 0.143]]

Error Relativo:
[[0.02 ]
 [0.001]
 [0.   ]]


In [159]:
# Ejercicio c - np.double

A = np.array([[3.03,-12.1,14],[-3.03,12.1,-7],[6.11,-14.2, 21]], dtype=np.double)
b = np.array([[-119],[120],[-139]], dtype=np.double)
Ab = np.array([[3.03,-12.1,14,-119],[-3.03,12.1,-7,120],[6.11,-14.2,21,-139]], dtype=np.double)

x = Gauss(Ab, np.double)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([0, 10, 1/7], dtype=np.double))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[ 0.   ]
 [10.   ]
 [ 0.143]]

Error Relativo:
[[0.]
 [0.]
 [0.]]


In [160]:
#linalg.solve
# half se aproxima al menos al valor real
print(linalg.solve(A,b))

[[2.965e-15]
 [1.000e+01]
 [1.429e-01]]


In [150]:
#============================= Ejercicio D =====================
# Ejercicio d - np.half
A = np.array([[3.3330,15920,10.333],[2.2220,16.710,9.6120],[-1.5611,5.1792,-1.6855]], dtype=np.half)
b = np.array([[7953],[0.965],[2.714]], dtype=np.half)
Ab = np.array([[3.3330,15920,10.333,7953],[2.2220,16.710,9.6120,0.965],[-1.5611,5.1792,-1.6855,2.714]], dtype=np.half)

x = Gauss(Ab, np.half)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([1, 0.5, -1], dtype=np.half))
print("\nError Relativo:\n{0}".format(resultado))



Soluciones:
[[ 2.494]
 [ 0.5  ]
 [-1.578]]

Error Relativo:
[[1.494]
 [0.   ]
 [0.578]]


In [151]:
# Ejercicio d - np.double
A = np.array([[3.3330,15920,10.333],[2.2220,16.710,9.6120],[-1.5611,5.1792,-1.6855]], dtype=np.double)
b = np.array([[7953],[0.965],[2.714]], dtype=np.double)
Ab = np.array([[3.3330,15920,10.333,7953],[2.2220,16.710,9.6120,0.965],[-1.5611,5.1792,-1.6855,2.714]], dtype=np.double)

x = Gauss(Ab, np.double)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([1, 0.5, -1], dtype=np.double))
print("\nError Relativo:\n{0}".format(resultado))



Soluciones:
[[ 1. ]
 [ 0.5]
 [-1. ]]

Error Relativo:
[[2.990e-13]
 [0.000e+00]
 [9.637e-14]]


In [152]:
#linalg.solve
#double tiene una mejor aproximacion a las soluciones reales
print(linalg.solve(A,b))

[[ 1. ]
 [ 0.5]
 [-1. ]]


In [153]:
#============================= Ejercicio E =====================
# Ejercicio e - np.half
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.110,-13.1,-1]], dtype=np.half)
b = np.array([[1.12],[3.44],[2.15],[4.16]], dtype=np.half)
Ab = np.array([[1.19,2.11,-100,1,1.12],[14.2,-0.122,12.2,-1,3.44],[0,100,-99.9,1,2.15],[15.3,0.110,-13.1,-1,4.16]], dtype=np.half)

x = Gauss(Ab, np.half)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([0.17682530, 0.01269269, -0.02065405, -1.18260870], dtype=np.half))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[ 0.176]
 [ 0.013]
 [-0.021]
 [-1.192]]

Error Relativo:
[[0.004]
 [0.001]
 [0.005]
 [0.008]]


In [161]:
# Ejercicio e - np.double
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.110,-13.1,-1]], dtype=np.double)
b = np.array([[1.12],[3.44],[2.15],[4.16]], dtype=np.double)
Ab = np.array([[1.19,2.11,-100,1,1.12],[14.2,-0.122,12.2,-1,3.44],[0,100,-99.9,1,2.15],[15.3,0.110,-13.1,-1,4.16]], dtype=np.double)

x = Gauss(Ab, np.double)
print("\nSoluciones:\n{0}".format(x))

resultado = errorRelativo(x, np.array([0.17682530, 0.01269269, -0.02065405, -1.18260870], dtype=np.double))
print("\nError Relativo:\n{0}".format(resultado))


Soluciones:
[[ 0.177]
 [ 0.013]
 [-0.021]
 [-1.183]]

Error Relativo:
[[1.414e-08]
 [6.836e-08]
 [6.639e-09]
 [3.832e-09]]


In [162]:
#linalg.solve

print(linalg.solve(A,b))

[[ 0.177]
 [ 0.013]
 [-0.021]
 [-1.183]]
